name: flutter_lucide_animated_example
description: "Example app for flutter_lucide_animated"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter
  flutter_lucide_animated:
    path: ../
  google_fonts: ^7.0.2
  adaptive_screen_utils: ^2.4.0
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
